channels:
  - conda-forge

dependencies:
  - python=3.6
  - sphinx=1.5
  - doxygen
  - pip
  - pip:
    - git+https://github.com/angus-g/sphinxcontrib-autodoc_doxygen.git#egg=sphinxcontrib-autodoc_doxygen
    - git+https://github.com/angus-g/sphinx-fortran.git#egg=sphinx-fortran
